name: Pick_some_member
on: 
  schedule:
    - cron: '42 10 * * mon' # Every monday at 10:42
  workflow_dispatch:


jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - run: pip install numpy pandas python-dotenv argparse
    - run: python main.py
      env:
        MEMBERS_SHEET_URL: ${{ secrets.MEMBERS_SHEET_URL }}
    - name: Create team sync issue
      run: gh issue create --title "$TITLE" --assignee "$ASSIGNEES"  --body "$BODY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        TITLE: "ENSPY AI : We Value Your Input"
        ASSIGNEES: hafro05,nprime496
        LABELS: weekly sync,docs-team
        BODY: |
          
          Hello @${{ env.user1 }},

          We're pleased to announce that you've been selected for an exciting opportunity within our community! As a valued member, we invite you to share your expertise by choosing to either write an article this week or deliver a presentation on a topic of your interest.
          
          Please let us know your preference by responding in the comments below, including your availability, preferred activity, and the topic you'd like to share with us. We are eagerly looking forward to your participation and the unique insights you will contribute to our community.
          
          Thank you for being a vital part of our community's journey.
          
          For more information, please visit [url].
          
          Best Regards,
          
          @ENSP-AI-Mentoring
        PINNED: false
        CLOSE_PREVIOUS: false


