name: Pick_some_member
on: 
  #schedule:
  #  - cron: '42 10 * * mon' # Every monday at 10:42
  workflow_dispatch:


jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - run: pip install numpy pandas python-dotenv argparse
    # - run: python main.py  --column_to_check availability_meeting
    #   env:
    #     MEMBERS_SHEET_URL: ${{ secrets.MEMBERS_SHEET_URL }}
    - name: Create team sync issue
      run: gh issue create --title "$TITLE"  --body "$BODY" #--label "$LABELS" --assignee "$ASSIGNEES" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        TITLE: "ENSPY AI [Meeting]: custom"
        #ASSIGNEES: "" #KameniAlexNea,nprime496,1001pepi
        #LABELS: meeting
        BODY: |
          
          Hello [custom]

          [custom]
                    
          Best Regards,
          
          @ENSP-AI-Mentoring
        PINNED: false
        CLOSE_PREVIOUS: false


